  mysql:
    image: mysql:8
    container_name: mysql_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rlaehdus00
      MYSQL_DATABASE: qampus
      MYSQL_USER: myuser
      MYSQL_PASSWORD: rlaehdus00
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=rlaehdus00"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: qampus-be
    container_name: qampus
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/qampus?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rlaehdus00
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql
