services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: qampus
      MYSQL_USER: myuser
      MYSQL_PASSWORD: rlaehdus00
      MYSQL_ROOT_PASSWORD: rlaehdus00
      TZ: Asia/Seoul
    networks:
      - springboot-mysql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["mysqld","--default-time-zone=Asia/Seoul"]
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  quampus-be:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["java", "-Xmx2g", "-jar", "/app.jar"]
    container_name: quampus-be
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/qampus
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: rlaehdus00
    networks:
      - springboot-mysql
    ports:
      - "9000:8082"
    restart: always
    
  visualvm-test:
    build: .
    container_name: visualvm-test
    ports:
      - "1098:1098"
      - "1099:1099"
      
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.port=1099
        -Dcom.sun.management.jmxremote.rmi.port=1098
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=42.82.219.16
    networks:
      - springboot-mysql
    logging:
      driver: "json-file"
      options:
        max-file: "100"
        max-size: "10m"



  redis:
    container_name: redis
    image: redis:latest
    networks:
      - springboot-mysql
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  springboot-mysql:
    driver: bridge

volumes:
  mysql-data:
