version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rlaehdus00
      MYSQL_DATABASE: qampus
      MYSQL_USER: myuser
      MYSQL_PASSWORD: rlaehdus00
    ports:
      - "3307:3306"
    networks:
      - springboot-mysql

  app:
    image: qampus-be
    container_name: qampus
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/qampus?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: rlaehdus00
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql

networks:
  springboot-mysql:
